### ISSUE TITLE
Throwing error Undefined property: craft\feedme\Plugin::$data after upgrade

### ISSUE THREAD

**Issue by bhashkar007** [engram-design/FeedMe#1463]
### Description
Recently, I updated a Craft v3.4.25 to Craft v4.10.0 and Feed Me to v5.5.0. It's all updated fine but while I am going to FeedMe dashboard, it's throwing HTTP ERROR 500 error. I checked `phperrors.log` and found this error:
```
Next Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Undefined property: craft\feedme\Plugin::$data"). in /var/www/html/vendor/craftcms/feed-me/src/templates/feeds/index.html:47
Stack trace:
#0 /var/www/html/storage/runtime/compiled_templates/b6/b6bbb0d43aaabe63a1b128d7c0c9f4a2.php(620): Twig\Template->displayBlock()
#1 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_04729c59bc44d9d02fe3d86b6c8e69bb->block_main()
#2 /var/www/html/storage/runtime/compiled_templates/b6/b6bbb0d43aaabe63a1b128d7c0c9f4a2.php(377): Twig\Template->displayBlock()
#3 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_04729c59bc44d9d02fe3d86b6c8e69bb->block_body()
#4 /var/www/html/storage/runtime/compiled_templates/f3/f3bce1afde2ae6b6f31c36eea07e6271.php(94): Twig\Template->displayBlock()
#5 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_b98fa283aae4c16ad9a9460dc06c38e8->doDisplay()
#6 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#7 /var/www/html/storage/runtime/compiled_templates/7f/7fbede1e4c67df24615b1956ead40bff.php(56): Twig\Template->display()
#8 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_3ac0435e7dfc28a419423783c166cfb2->doDisplay()
#9 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#10 /var/www/html/storage/runtime/compiled_templates/b6/b6bbb0d43aaabe63a1b128d7c0c9f4a2.php(180): Twig\Template->display()
#11 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_04729c59bc44d9d02fe3d86b6c8e69bb->doDisplay()
#12 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#13 /var/www/html/storage/runtime/compiled_templates/50/506acb0b1ef7551838b20087a7afefa8.php(57): Twig\Template->display()
#14 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_c703f804586b50b3fe715be7044a1c78->doDisplay()
#15 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#16 /var/www/html/storage/runtime/compiled_templates/8b/8b630c1d6f0791d2f92fa05521278095.php(69): Twig\Template->display()
#17 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_a15af9abd573b396cac14c11d4f7d4a3->doDisplay()
#18 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#19 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#20 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render()
#21 /var/www/html/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render()
#22 /var/www/html/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render()
#23 /var/www/html/vendor/craftcms/cms/src/web/View.php(535): craft\web\View->renderTemplate()
#24 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate()
#25 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format()
#26 /var/www/html/vendor/craftcms/cms/src/web/Response.php(338): yii\web\Response->prepare()
#27 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#28 /var/www/html/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#29 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(192): yii\web\ErrorHandler->renderException()
#30 /var/www/html/vendor/yiisoft/yii2/base/ErrorHandler.php(323): craft\web\ErrorHandler->renderException()
#31 [internal function]: yii\base\ErrorHandler->handleFatalError()
#32 {main}
  thrown in /var/www/html/vendor/craftcms/feed-me/src/templates/feeds/index.html on line 47
  ```

### Steps to reproduce

1. Update Craft to v4.10.0
2. Update Feed Me plugin to 5.5.0

### Additional info

- Craft version: 4.10.0
- PHP version: 8.1.2
- Database driver & version: MySQL 8.0.37
- Plugins & versions: Feed Me v5.5.0

**Comment by bhashkar007** [comment]
This problem wasn't related to Feed Me plugin. There was a custom data type for Feed Me and was having incompatible code `Declaration of modules\CrUtility\datatypes\BaseplateCsvDataType::getFeed($url, $settings, $usePrimaryElement = true) must be compatible with craft\feedme\base\DataTypeInterface::getFeed($url, $settings, bool $usePrimaryElement = true): mixed` I fixed this issue.
